select W.BRAND, COUNT(W.BRAND) AS COUNT_ --COUNT(*) AS COUNT_ OLARAKTA YAPILABÝLÝR
FROM WEBOFFERS W
GROUP BY W.BRAND
ORDER BY COUNT_ DESC

--SORU2
select BRAND, COUNT(*) AS COUNT_ , 
ROUND(CONVERT(FLOAT,COUNT(*))/(SELECT COUNT(*) FROM WEBOFFERS)*100,2) AS PERCENT_

--ROUND(CONVERT(FLOAT,COUNT(*))/30229*100,2)
FROM WEBOFFERS 
GROUP BY BRAND
ORDER BY COUNT_ DESC

--SORU3
SELECT C.CITY, COUNT(W.BRAND)AS COUNT_
FROM WEBOFFERS W
INNER JOIN CITY C
ON C.ID=W.CITYID
GROUP BY C.CITY
ORDER BY 2 DESC


SELECT CITY,
(SELECT COUNT(*) FROM WEBOFFERS WHERE CITYID=C.ID) AS COUNT_
FROM CITY C
ORDER BY 2 DESC

--SORU4
SELECT *
FROM WEBOFFERS W
INNER JOIN CITY C ON W.CITYID= C.ID
INNER JOIN TOWN T ON T.ID=W.TOWNID
INNER JOIN DISTRICT D ON D.ID=W.DISTRICTID
INNER JOIN USER_ U ON U.ID=W.USERID
WHERE C.CITY= 'iSTANBUL'
AND W.SHIFTTYPE IN ('Yarý Otomatik Vites','Otomatik Vites')
AND W.BRAND='Volkswagen' and W.MODEL='Passat'
AND W.FUEL='Dizel' and W.FROMWHO='Sahibinden'
AND W.YEAR_ BETWEEN 2014 and 2018

--soru5
SELECT *
FROM WEBOFFERS W
INNER JOIN CITY C ON W.CITYID= C.ID
INNER JOIN TOWN T ON T.ID=W.TOWNID
INNER JOIN DISTRICT D ON D.ID=W.DISTRICTID
INNER JOIN USER_ U ON U.ID=W.USERID
WHERE W.BRAND= 'BMW' 
and C.CITY IN
(SELECT value FROM string_split('ANKARA ,ÝSTANBUL,ÝZMÝR',','))