--SORU1
select CITY, SUM(LINETOTAL) AS TOTALSALE
from SALEORDERS 
GROUP BY CITY
ORDER BY CITY
--SORU2
SELECT CITY, MONTH_, SUM(LINETOTAL) AS TOTALSALE
FROM SALEORDERS
GROUP BY CITY, MONTH_
--SORU3
SELECT CITY, DAYOFWEEK_,SUM(LINETOTAL) AS TOTALSALE
FROM SALEORDERS
GROUP BY CITY, DAYOFWEEK_
ORDER BY CITY, DAYOFWEEK_
--SORU4   DISTINCT ÞEHIR TEKRAR ETMEZ 1 TANE OLUR
SELECT DISTINCT CITY,
( SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='01.PZT') AS PAZARTESI,
( SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE  CITY=S.CITY AND DAYOFWEEK_='02.SAL') AS SALI
FROM SALEORDERS S
--SORU5  ANLAMADI TEKRAR BAK
SELECT TOP 5
 CITY, CATEGORY1, SUM(LINETOTAL) AS TOTALSALE


FROM SALEORDERS S
CROSS APPLY()

WHERE CITY='ADANA'
GROUP BY CITY, CATEGORY1
ORDER BY SUM(LINETOTAL) DESC

--6 anlamadým chatten bak

--56
SELECT TOP 100
U.USERNAME_, U.NAMESURNAME, U.TELNR1, U.TELNR2,
C.COUNTRY, CT.CITY, T.TOWN, ADR.ADDRESSTEXT,
O.ID, ITM.ITEMCODE, ITM.ITEMNAME, ITM.BRAND, ITM.CATEGORY1,
ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4,
OD.AMOUNT, OD.UNITPRICE,OD.LINETOTAL, CONVERT(DATE, O.DATE_) AS DATE, 
CONVERT(TIME, O.DATE_) AS ORDERTIME,
YEAR(O.DATE_) AS YEAR_, DATENAME(MONTH, O.DATE_) AS MONTH_ , DATENAME(DW,O.DATE_) AS DAYOFWEEK_
FROM ORDERS O
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON O.USERID=U.ID
INNER JOIN ADDRESS ADR ON ADR.ID=O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID= ADR.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=ADR.CITYID
INNER JOIN TOWNS T ON T.ID=ADR.TOWNID

--7.SORU
SELECT * FROM CITIES
CREATE TABLE CITIES2 (ID INT IDENTITY(1,1) , COUNTRYID INT,CITY VARCHAR(50))
SELECT * FROM CITIES2
INSERT INTO CITIES2 (COUNTRYID,CITY)SELECT COUNTRYID,CITY FROM CITIES
SELECT * FROM CITIES2
DROP TABLE CITIES2
--BÝR TABLODAKÝ VERÝLEÝRN HEPSÝNÝ DÝÐER TABLOYA ATMAK ÝÇÝN  CTRL H ÝLE
SELECT * INTO CITIES2 FROM CITIES --JOINLER BUNUN SONUNA GELECEK

--8.SORU
SET STATISTICS IO ON

select CT.CITY, SUM(O.TOTALPRICE) 
FROM ORDERS O
INNER JOIN ADDRESS ADR
ON ADR.ID=O.ADDRESSID
INNER JOIN CITIES CT
ON ADR.CITYID= CT.ID
GROUP BY CT.CITY
--BU NE KADAR UÐRAÞILDIÐINI GÖSTERÝYOR.
SET STATISTICS IO ON
SELECT *,
(SELECT SUM(TOTALPRICE) FROM ORDERS WHERE ADDRESSID IN
	(SELECT ID FROM ADDRESS WHERE CITYID=C.ID
	) )
FROM CITIES C

--10.soru
select 
ITM.BRAND,ITM.CATEGORY1,SUM(OD.LINETOTAL) AS TOTALPRICE
from ORDERDETAILS OD
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY ITM.BRAND, ITM.CATEGORY1
ORDER BY 1

SELECT BRAND, CATEGORY1,
(SELECT SUM(LINETOTAL)FROM ORDERDETAILS WHERE ITEMID IN
	(SELECT ID FROM ITEMS WHERE BRAND=ITM.BRAND AND CATEGORY1=ITM.CATEGORY1)

)AS TOTALPRICE
FROM ITEMS ITM

GROUP BY BRAND

--11.SORU
SELECT ITM.CATEGORY1, ITM.BRAND, SUM(OD.LINETOTAL) AS TOTALPRICE
FROM 
ORDERDETAILS OD
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY ITM.CATEGORY1, ITM.BRAND
ORDER BY ITM.CATEGORY1, SUM(OD.LINETOTAL) DESC

--12.SORU
SELECT IT.BRAND, IT.CATEGORY1, IT.ITEMCODE, IT.ITEMNAME,
COUNT(OD.ID) AS SALECOUNT, SUM(OD.AMOUNT) AS TOTALAMOUNT,
MIN(OD.UNITPRICE) AS MINPRICE, MAX(OD.UNITPRICE) AS MAXPRICE,
AVG(OD.UNITPRICE) AS AVGPRICE
FROM ITEMS IT
INNER JOIN ORDERDETAILS OD
ON OD.ITEMID= IT.ID
GROUP BY IT.BRAND, IT.CATEGORY1, IT.ITEMCODE, IT.ITEMNAME

--13.SORU
SELECT U.ID,U.NAMESURNAME,
( SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID) AS ADDRESSCOUNT,
(
SELECT ADDRESSTEXT FROM ADDRESS WHERE ID IN
	( SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID= U.ID ORDER BY DATE_ DESC)
)
FROM USERS U


SELECT * FROM ORDERS WHERE USERID= 1 ORDER BY DATE_ DESC
SELECT * FROM ADDRESS WHERE ID=3

--14.SORU
SELECT U.ID,U.NAMESURNAME,
( SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID) AS ADDRESSCOUNT,
(
SELECT ADDRESSTEXT FROM ADDRESS WHERE ID IN
	( SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID= U.ID ORDER BY DATE_ DESC)
)

FROM USERS U

--15.SORU